name: CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build
      env:
        REACT_APP_MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
        REACT_APP_ROUTE: ${{ secrets.ROUTE }}
        CI: false

    - name: Test
      run: |
        npm test

