name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run build
      env:
        REACT_APP_MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
        REACT_APP_ROUTE: ${{ secrets.ROUTE }}
        CI: false

    - name: Test
      run: |
        npm test

  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "sero-can-staging"
          heroku_email: "abeljohnjoseph@gmail.com"
