name: Deploy to Staging
on:
  push:
    branches:
      - staging


jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.0.4
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "serotracker-staging"
          heroku_email: "abeljohnjoseph@gmail.com"
